name: popquiz

description: Projeto Seletivo ChekMob Fernando Craveiro

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  lottie: ^1.2.1
  #get: ^4.5.1
  #get_storage: ^2.0.3
  google_fonts: ^2.2.0
  supabase: ^0.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/imagens/
